name: test1

on:
  push: 
    branches: [ main ]
  pull_request:
    types: [opened, reopened]
    branches: [main]
  
jobs:
  Job_Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: temurin
          cache: maven
      - name: Make mvnw executable
        run: chmod +x ./mvnw
      - name: Job maven_Build
        run: ./mvnw compile

  Job_Verify:
    needs: Job_Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: temurin
          cache: maven
      - name: Make mvnw executable
        run: chmod +x ./mvnw
      - name: Job Maven_Verify
        run: ./mvnw verify

  Job_Upload_Jacoco:
    needs: Job_Verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Archive coverage report
        uses: actions/upload-artifact@v7
        with:
          name: Upload Jacoco
          path: .\target\site\jacoco\jacoco.xml
          archive: false 

  # Job_Dowload_Jacoco:
  #   needs: Job_Upload_Jacoco
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Dossier avant  DL
  #       run: ls -lah
  #     - name: Download Artifact step 2
  #       uses: actions/download-artifact@v8
  #       with:
  #         name: download Jacoco
  #         path: ./
  #     - name: Dossier après DL
  #       run: ls -lah