name: test1

on:
  push: 
    branches: [ main ]
  pull_request:
    types: [opened, reopened]
    branches: [main]
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@main
      with:
        extra_args: --results=verified,unknown

  build:
    needs: test
    name: Lint
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      # contents permission to clone the repository
      contents: read
      packages: read
      # issues and pull-requests permissions to write results as pull
      # request comments. Omit them if you don't need summary comments
      issues: write
      pull-requests: write
      # To report GitHub Actions status checks. Omit if you don't need
      # to update commit status
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0
          persist-credentials: false

      - name: Super-linter
        uses: super-linter/super-linter@v8.6.0 # x-release-please-version
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Job_Build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: temurin
          cache: maven
      - name: Make mvnw executable
        run: chmod +x ./mvnw
      - name: Job maven_Build
        run: ./mvnw compile
      - name: Classes report
        uses: actions/upload-artifact@v7
        with:
          name: Upload Classes
          path: ./target/classes/*

  Job_Verify:
    needs: Job_Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: temurin
          cache: maven
      - name: Make mvnw executable
        run: chmod +x ./mvnw
      - name: Job Maven_Verify
        run: ./mvnw verify
      - name: Archive coverage report
        uses: actions/upload-artifact@v7
        with:
          name: Jacoco
          path: ./target/site/jacoco/jacoco.xml
          archive: false 
  
  sonarqube:
    needs: Job_Verify
    runs-on: ubuntu-latest
    steps:
      - name: Download Classes
        uses: actions/download-artifact@v8
        with:
          name: Upload Classes
          path: ./Classes
      - name: Download Classes
        uses: actions/download-artifact@v8
        with:
          name: jacoco.xml
          path: ./
      - uses: actions/checkout@v6
        with:
        # Disabling shallow clones is recommended for improving the relevancy of reporting
          fetch-depth: 0
      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=Laurent28250
            -Dsonar.projectKey=laurent28250
            -Dsonar.coverage.jacoco.xmlReportPaths=./jacoco.xml
            -Dsonar.sources=./Classes